### ISSUE TITLE
Error on 

### ISSUE THREAD

**Issue by ikrivosheev** [mdsteele/rust-cab#9]
After merge the PR: https://github.com/mdsteele/rust-cab/pull/8 , I get panick
```rust
thread 'main' panicked at 'assertion failed: bits <= 16', /home/ikrivosheev/.cargo/registry/src/github.com-1ecc6299db9ec823/lzxd-0.1.2/src/bitstream.rs:60:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:50:5
   3: lzxd::bitstream::Bitstream::read_bits
   4: lzxd::block::decode_element
   5: lzxd::Lzxd::decompress_next
   6: cab::internal::cabinet::FolderReader<R>::load_block
   7: std::io::copy::stack_buffer_copy
   8: <engine::unpacker::CABFilesIterator as engine::unpacker::FilesIterator>::next
```

I can link a file that reproduces the error.

**Comment by mdsteele** [comment]
Yes, could you please link a file that reproduces the error?

**Comment by DrChat** [comment]
I've fixed this issue upstream in LZXD: https://github.com/Lonami/lzxd/pull/6
Need to bump the version number so you guys can upgrade.

**Comment by ikrivosheev** [comment]
@mdsteele I cannot link into issue, because is too big. I put this file into dropbox: https://www.dropbox.com/s/a3qb6diujyogt4j/774933618e84bb5566de1c936bddefae3b097a6a6c8e5607e64d21e38d43aa3b?dl=0
